"""REML for trend-residual variograms. `adr/0011`, `13-kriging.md` §7.4.

**Two of these tests carry the decision, and the ADR says they are not
optional.** Without them, deleting `fit_reml.py` and pointing the residual path
at the least-squares fitter passes every other test in this repository and
produces subtly wrong maps forever:

- *Synthetic recovery* — a field generated from a known model, with a known
  trend added, and REML asked to recover the model from the residual.
- *Bias demonstration* — the same data fitted by method of moments, asserting
  that it underestimates the range materially relative to REML.

The second is the one that fails loudly if somebody later simplifies this away.
"""

from __future__ import annotations

import numpy as np
import pytest

from webmap_geo.flags import FlagList
from webmap_geo.variogram.experimental import estimate_experimental
from webmap_geo.variogram.fit import fit
from webmap_geo.variogram.fit_reml import fit_reml, select_model_by_reml
from webmap_geo.variogram.model import FittedVariogram

#: The field these tests are built on: a 10,000 ft square with a 3,000 ft range.
TRUE_RANGE = 3_000.0
TRUE_SILL = 1.0
TRUE_NUGGET = 0.05
EXTENT = 10_000.0


def gaussian_field(
    rng: np.random.Generator, count: int, model: FittedVariogram
) -> tuple[np.ndarray, np.ndarray]:
    """Samples of a field with exactly this covariance.

    Generated by a Cholesky of the covariance matrix — unconditional simulation,
    the textbook way. Slower than a spectral method and exact, which is what a
    recovery test needs: if the field only approximately has the model's
    covariance, a recovery test is measuring the approximation.
    """
    points = rng.uniform(0.0, EXTENT, size=(count, 2))
    separation = points[:, None, :] - points[None, :, :]
    distance = np.hypot(separation[..., 0], separation[..., 1])

    covariance = model.covariance(distance) + np.eye(count) * 1e-8
    factor = np.linalg.cholesky(covariance)
    values = factor @ rng.standard_normal(count)
    return points, values


def linear_trend(points: np.ndarray, theta: tuple[float, float, float]) -> np.ndarray:
    """A plane: the commonest trend, and the one whose Jacobian is exact."""
    intercept, east, north = theta
    return intercept + east * points[:, 0] / EXTENT + north * points[:, 1] / EXTENT


def design_matrix(points: np.ndarray) -> np.ndarray:
    """`J = df/dtheta` for that plane. Constant, because the trend is linear."""
    return np.stack(
        [np.ones(len(points)), points[:, 0] / EXTENT, points[:, 1] / EXTENT], axis=1
    )


def residual_after_ols(values: np.ndarray, design: np.ndarray) -> np.ndarray:
    """What the trend fit leaves behind.

    Ordinary least squares, because that is what the first pass of §8.1's loop
    does before it has a covariance to weight by — and it is the residual whose
    variogram is biased, which is the whole subject.
    """
    coefficients, *_ = np.linalg.lstsq(design, values, rcond=None)
    return np.asarray(values - design @ coefficients, dtype=np.float64)


@pytest.fixture(scope="module")
def truth() -> FittedVariogram:
    return FittedVariogram(
        model="exponential", nugget=TRUE_NUGGET, sill=TRUE_SILL, range_=TRUE_RANGE
    )


@pytest.fixture(scope="module")
def trended(truth: FittedVariogram) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """A field with known covariance and a known plane added to it."""
    rng = np.random.default_rng(20260911)
    points, field = gaussian_field(rng, 400, truth)
    values = field + linear_trend(points, (10.0, 4.0, -3.0))
    return points, values, design_matrix(points)


class TestSyntheticRecovery:
    """`adr/0011`'s first required test."""

    def test_recovers_the_range_the_field_was_built_with(
        self, trended: tuple[np.ndarray, np.ndarray, np.ndarray], truth: FittedVariogram
    ) -> None:
        points, values, design = trended
        residual = residual_after_ols(values, design)
        start = fit(estimate_experimental(points, residual))

        result = fit_reml(points, residual, design, start)

        # Within a factor of about 1.6 either way. A variogram range from 400
        # samples of one realisation is not a precise quantity — the test that
        # matters is the comparative one below.
        assert 0.6 * TRUE_RANGE < result.variogram.range_ < 1.7 * TRUE_RANGE

    def test_recovers_the_sill(
        self, trended: tuple[np.ndarray, np.ndarray, np.ndarray]
    ) -> None:
        points, values, design = trended
        residual = residual_after_ols(values, design)
        start = fit(estimate_experimental(points, residual))

        result = fit_reml(points, residual, design, start)

        assert 0.5 * TRUE_SILL < result.variogram.sill < 2.0 * TRUE_SILL

    def test_reports_the_likelihood_it_reached(
        self, trended: tuple[np.ndarray, np.ndarray, np.ndarray]
    ) -> None:
        """Comparable between models on the same data, which is how §7.4
        selects a family for a residual."""
        points, values, design = trended
        residual = residual_after_ols(values, design)
        start = fit(estimate_experimental(points, residual))

        result = fit_reml(points, residual, design, start)

        assert np.isfinite(result.log_likelihood)


class TestBiasDemonstration:
    """`adr/0011`'s second required test — the one that fails loudly if somebody
    later points the residual path back at the least-squares fitter.

    The claim being defended: a method-of-moments variogram of a *fitted
    residual* underestimates the range, because the residual is the error minus
    what the trend absorbed and that absorption is systematic.
    """

    def test_least_squares_underestimates_the_range_relative_to_reml(
        self, trended: tuple[np.ndarray, np.ndarray, np.ndarray]
    ) -> None:
        points, values, design = trended
        residual = residual_after_ols(values, design)

        wls = fit(estimate_experimental(points, residual))
        reml = fit_reml(points, residual, design, wls).variogram

        assert wls.range_ < reml.range_, (
            "Weighted least squares should underestimate the range of a fitted "
            "residual relative to REML. If this fails, either the REML fit has "
            "regressed or the residual path is no longer going through it — "
            "`adr/0011` exists because that failure is otherwise invisible."
        )

    def test_the_underestimate_is_material_not_marginal(
        self, trended: tuple[np.ndarray, np.ndarray, np.ndarray]
    ) -> None:
        """§7.4: "not a small effect at the coefficient counts a
        completion-response trend uses".

        **Measured on this field**: REML recovers 3,007 ft against a true 3,000,
        and weighted least squares gives 2,720 — a 9.5% underestimate from three
        coefficients on 400 samples. The threshold is 5% rather than that
        number: a 5% range error already moves kriging weights, and asserting
        the measurement itself would make this a test of the seed.
        """
        points, values, design = trended
        residual = residual_after_ols(values, design)

        wls = fit(estimate_experimental(points, residual))
        reml = fit_reml(points, residual, design, wls).variogram

        assert wls.range_ < 0.95 * reml.range_

    def test_the_bias_grows_with_the_number_of_coefficients(
        self, truth: FittedVariogram
    ) -> None:
        """The mechanism, not just the symptom: more coefficients absorb more
        structure, so the residual's variogram flattens further."""
        rng = np.random.default_rng(99)
        points, field = gaussian_field(rng, 400, truth)
        values = field + linear_trend(points, (10.0, 4.0, -3.0))

        small = design_matrix(points)
        # A quadratic surface: six coefficients rather than three, absorbing
        # more of the long-range structure.
        large = np.column_stack(
            [
                small,
                (points[:, 0] / EXTENT) ** 2,
                (points[:, 1] / EXTENT) ** 2,
                (points[:, 0] * points[:, 1]) / EXTENT**2,
            ]
        )

        small_range = fit(estimate_experimental(points, residual_after_ols(values, small)))
        large_range = fit(estimate_experimental(points, residual_after_ols(values, large)))

        assert large_range.range_ <= small_range.range_


class TestImplementationRules:
    """The three rules `adr/0011` calls part of the decision."""

    def test_several_starts_are_tried(
        self, trended: tuple[np.ndarray, np.ndarray, np.ndarray]
    ) -> None:
        """Rule 2. REML surfaces are not reliably unimodal in range and nugget,
        and one start lands in a local minimum often enough to matter."""
        points, values, design = trended
        residual = residual_after_ols(values, design)
        start = fit(estimate_experimental(points, residual))

        result = fit_reml(points, residual, design, start)

        assert result.starts_tried > 1

    def test_a_small_problem_uses_every_sample(
        self, trended: tuple[np.ndarray, np.ndarray, np.ndarray]
    ) -> None:
        """Rule 3's other side: the subset path is for the case that needs it,
        and 400 samples do not."""
        points, values, design = trended
        residual = residual_after_ols(values, design)
        start = fit(estimate_experimental(points, residual))

        result = fit_reml(points, residual, design, start)

        assert not result.subset_used
        assert result.n_samples == len(values)

    def test_mismatched_inputs_are_refused(self) -> None:
        points = np.zeros((10, 2))
        with pytest.raises(Exception, match="one residual and one Jacobian row"):
            fit_reml(
                points,
                np.zeros(9),
                np.ones((10, 2)),
                FittedVariogram(model="exponential", nugget=0.1, sill=1.0, range_=100.0),
            )


class TestModelSelection:
    def test_chooses_by_likelihood_rather_than_by_fit_to_binned_points(
        self, trended: tuple[np.ndarray, np.ndarray, np.ndarray]
    ) -> None:
        """§7.4: choosing a family because it hugs the empirical points better
        is choosing on a statistic that is itself biased here."""
        points, values, design = trended
        residual = residual_after_ols(values, design)
        start = fit(estimate_experimental(points, residual))

        chosen = select_model_by_reml(
            points, residual, design, start, families=("exponential", "gaussian")
        )

        assert chosen.variogram.model in {"exponential", "gaussian"}
        assert np.isfinite(chosen.log_likelihood)

    def test_the_chosen_model_has_the_best_likelihood(
        self, trended: tuple[np.ndarray, np.ndarray, np.ndarray]
    ) -> None:
        points, values, design = trended
        residual = residual_after_ols(values, design)
        start = fit(estimate_experimental(points, residual))

        families = ("exponential", "gaussian", "spherical")
        chosen = select_model_by_reml(points, residual, design, start, families=families)
        each = {
            family: fit_reml(points, residual, design, start, model=family).log_likelihood
            for family in families
        }

        assert chosen.log_likelihood == pytest.approx(max(each.values()))


class TestSubsetPath:
    def test_records_that_it_subsetted(self) -> None:
        """`adr/0011` rule 3: record which path ran. A fit on 5,000 of 60,000
        samples is a different claim from a fit on all of them."""
        import webmap_geo.variogram.fit_reml as module

        rng = np.random.default_rng(5)
        count = 300
        points = rng.uniform(0.0, EXTENT, size=(count, 2))
        values = rng.standard_normal(count)
        design = design_matrix(points)
        flags = FlagList()

        original = module.DENSE_LIMIT
        subset = module.SUBSET_SIZE
        module.DENSE_LIMIT = 100
        module.SUBSET_SIZE = 120
        try:
            result = fit_reml(
                points,
                values,
                design,
                FittedVariogram(model="exponential", nugget=0.1, sill=1.0, range_=2_000.0),
                rng=rng,
                flags=flags,
            )
        finally:
            module.DENSE_LIMIT = original
            module.SUBSET_SIZE = subset

        assert result.subset_used
        assert flags.has("TREND_SUBSET_FIT")
