"""Variogram estimation and fitting. `05-geoprocessing.md` §6.3.

`CLAUDE.md` §6.1 sets the highest bar in the repo for `webmap_geo`: reference
comparison plus property tests. There is no Surfer reference to hand here, so
the standard applied instead is **recovery of a known field** — generate data
from a variogram with stated parameters, fit it back, and require the fit to
land near the truth. That is a stronger check than agreeing with another
implementation, because it can fail even when two implementations agree.
"""

from __future__ import annotations

import numpy as np
import pytest

from webmap_geo.exceptions import DegenerateInput
from webmap_geo.variogram import (
    ExperimentalVariogram,
    FittedVariogram,
    anisotropy_transform,
    declustering_weights,
    estimate_experimental,
    fit,
    fit_auto,
)

SEED = 20260909


def gaussian_field(
    rng: np.random.Generator,
    *,
    n: int = 400,
    extent: float = 20_000.0,
    range_: float = 4_000.0,
    sill: float = 10.0,
    nugget: float = 0.0,
    model: str = "spherical",
    anisotropy_ratio: float = 1.0,
    anisotropy_angle: float = 0.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Points and values drawn from a known variogram.

    Generated by Cholesky factorisation of the covariance matrix — the
    textbook construction, and importantly *not* the estimator under test. A
    field built by the same code that fits it would prove only self-consistency.
    """
    points = rng.uniform(0.0, extent, size=(n, 2))

    truth = FittedVariogram(
        model=model,
        nugget=nugget,
        sill=sill,
        range_=range_,
        anisotropy_ratio=anisotropy_ratio,
        anisotropy_angle=anisotropy_angle,
    )

    working = points
    if anisotropy_ratio > 1.0:
        working = points @ anisotropy_transform(anisotropy_ratio, anisotropy_angle).T

    separation = working[:, None, :] - working[None, :, :]
    distance = np.hypot(separation[..., 0], separation[..., 1])
    covariance = truth.covariance(distance)
    # A small ridge: the covariance matrix is positive *semi*-definite in
    # exact arithmetic and rounding can push it indefinite, which fails
    # Cholesky for reasons that have nothing to do with the model.
    covariance += np.eye(n) * 1e-8 * sill

    lower = np.linalg.cholesky(covariance)
    values = lower @ rng.standard_normal(n) + 100.0
    return points, values


# --- models ------------------------------------------------------------------


@pytest.mark.parametrize("model", ["spherical", "exponential", "gaussian"])
def test_gamma_is_zero_at_zero_lag(model: str) -> None:
    """**Not the nugget.** The nugget is a limit as h approaches zero, and a
    kriging system with gamma(0) = nugget on its diagonal is singular — which
    surfaces as a LinAlgError deep in the solver rather than as anything about
    variograms."""
    variogram = FittedVariogram(model=model, nugget=2.0, sill=10.0, range_=1_000.0)

    assert variogram.gamma(np.array([0.0]))[0] == 0.0
    assert variogram.gamma(np.array([1e-9]))[0] == pytest.approx(2.0, abs=0.01)


@pytest.mark.parametrize("model", ["spherical", "exponential", "gaussian"])
def test_gamma_rises_monotonically_to_the_sill(model: str) -> None:
    variogram = FittedVariogram(model=model, nugget=1.0, sill=10.0, range_=1_000.0)
    lags = np.linspace(1.0, 4_000.0, 200)

    gamma = variogram.gamma(lags)

    assert np.all(np.diff(gamma) >= -1e-9), "semivariance decreased with distance"
    assert gamma[-1] <= 10.0 + 1e-9


def test_spherical_reaches_the_sill_exactly_at_the_range() -> None:
    """The property that distinguishes it from exponential, and the reason a
    geologist picks one over the other."""
    variogram = FittedVariogram(model="spherical", nugget=0.0, sill=10.0, range_=1_000.0)

    assert variogram.gamma(np.array([1_000.0]))[0] == pytest.approx(10.0)
    assert variogram.gamma(np.array([999.0]))[0] < 10.0
    assert variogram.gamma(np.array([5_000.0]))[0] == pytest.approx(10.0)


def test_exponential_range_is_the_practical_range() -> None:
    """`range_` means the lag at 95% of the sill, not the e-folding distance.

    Without the factor of 3 in the exponent the two differ threefold, and
    every fitted range would silently read as a third of what a geologist
    means by it.
    """
    variogram = FittedVariogram(model="exponential", nugget=0.0, sill=10.0, range_=1_000.0)

    assert variogram.gamma(np.array([1_000.0]))[0] == pytest.approx(9.5, abs=0.1)


def test_covariance_and_semivariance_are_complements() -> None:
    """Kriging is solved in covariance form, so the two must agree exactly or
    the system being solved is not the model that was fitted."""
    variogram = FittedVariogram(model="spherical", nugget=1.0, sill=10.0, range_=800.0)
    lags = np.linspace(0.0, 2_000.0, 50)

    assert np.allclose(variogram.covariance(lags) + variogram.gamma(lags), 10.0)


def test_a_negative_variance_is_refused() -> None:
    with pytest.raises(DegenerateInput, match="variances"):
        FittedVariogram(model="spherical", nugget=-1.0, sill=10.0, range_=100.0)


def test_a_zero_range_says_what_it_would_mean() -> None:
    with pytest.raises(DegenerateInput, match="global mean"):
        FittedVariogram(model="spherical", nugget=0.0, sill=10.0, range_=0.0)


def test_an_inverted_anisotropy_ratio_names_the_fix() -> None:
    with pytest.raises(DegenerateInput, match="rotate the azimuth"):
        FittedVariogram(
            model="spherical", nugget=0.0, sill=10.0, range_=100.0, anisotropy_ratio=0.5
        )


# --- anisotropy transform ----------------------------------------------------


def test_the_azimuth_is_clockwise_from_north() -> None:
    """**A geologist's convention, not the mathematician's.**

    035 means north-northeast. Getting this backwards puts the variogram's
    major axis across the structural grain rather than along it, and the
    resulting map looks entirely plausible.
    """
    # A due-north major axis with a 4:1 ratio: a north-south separation should
    # be unchanged, an east-west one stretched fourfold.
    transform = anisotropy_transform(ratio=4.0, angle_deg=0.0)

    north = np.array([0.0, 1_000.0]) @ transform.T
    east = np.array([1_000.0, 0.0]) @ transform.T

    assert np.hypot(*north) == pytest.approx(1_000.0)
    assert np.hypot(*east) == pytest.approx(4_000.0)


def test_a_045_azimuth_stretches_across_the_northeast_grain() -> None:
    transform = anisotropy_transform(ratio=3.0, angle_deg=45.0)

    along = np.array([700.0, 700.0]) @ transform.T
    across = np.array([700.0, -700.0]) @ transform.T

    assert np.hypot(*along) == pytest.approx(np.hypot(700.0, 700.0), rel=1e-9)
    assert np.hypot(*across) == pytest.approx(3.0 * np.hypot(700.0, 700.0), rel=1e-9)


# --- declustering ------------------------------------------------------------


def test_declustering_downweights_a_pad() -> None:
    """**Why this matters more than people expect.**

    Well control is clustered by development history, not by geology. Twelve
    wells on a pad contribute hundreds of near-zero-lag pairs that describe
    drilling economics, and without declustering the variogram reports their
    similarity as a nugget.
    """
    rng = np.random.default_rng(SEED)
    pad = rng.uniform(0.0, 200.0, size=(12, 2))
    scattered = rng.uniform(0.0, 20_000.0, size=(20, 2))
    points = np.vstack([pad, scattered])

    weights = declustering_weights(points)

    assert weights[:12].mean() < weights[12:].mean() / 2, "the pad was not downweighted"


def test_declustering_leaves_an_even_survey_alone() -> None:
    """A grid of wells has no clustering to correct, and a correction applied
    anyway would be a distortion introduced by the estimator."""
    x, y = np.meshgrid(np.arange(10) * 1_000.0, np.arange(10) * 1_000.0)
    points = np.column_stack([x.ravel(), y.ravel()])

    weights = declustering_weights(points)

    assert weights.std() < 0.1


def test_weights_sum_to_the_point_count() -> None:
    """Which is what keeps a weighted variance comparable to an ordinary one."""
    rng = np.random.default_rng(SEED)
    points = rng.uniform(0.0, 10_000.0, size=(200, 2))

    weights = declustering_weights(points)

    assert weights.sum() == pytest.approx(200.0)


# --- experimental estimation -------------------------------------------------


def test_the_experimental_variogram_rises_and_flattens() -> None:
    """The shape every fitted model is trying to match. If this is wrong,
    nothing downstream can be right."""
    rng = np.random.default_rng(SEED)
    points, values = gaussian_field(rng, n=500, range_=4_000.0, sill=10.0)

    experimental = estimate_experimental(points, values, rng=rng)

    early = experimental.gamma[:3].mean()
    late = experimental.gamma[-3:].mean()
    assert early < late, "semivariance did not increase with lag"
    assert late == pytest.approx(experimental.sample_variance, rel=0.6)


def test_estimation_is_reproducible() -> None:
    """`CLAUDE.md` §3.3. Two runs of the same job must produce the same
    variogram, or the lineage record cannot reproduce the grid."""
    points, values = gaussian_field(np.random.default_rng(SEED), n=300)

    first = estimate_experimental(points, values, rng=np.random.default_rng(7))
    second = estimate_experimental(points, values, rng=np.random.default_rng(7))

    assert np.array_equal(first.gamma, second.gamma)
    assert np.array_equal(first.lags, second.lags)


def test_a_large_dataset_is_subsampled_rather_than_refused() -> None:
    """Subsampling is mandatory at this scale (§6.3): all-pairs on 500,000
    points is 1.25e11 distances."""
    rng = np.random.default_rng(SEED)
    points = rng.uniform(0.0, 50_000.0, size=(30_000, 2))
    values = rng.standard_normal(30_000)

    experimental = estimate_experimental(points, values, subsample=2_000, rng=rng)

    assert experimental.n_points_used == 2_000


def test_too_few_points_says_how_many_are_needed() -> None:
    rng = np.random.default_rng(SEED)
    with pytest.raises(DegenerateInput, match="fewer than about 30"):
        estimate_experimental(rng.uniform(size=(5, 2)), rng.standard_normal(5))


def test_mismatched_points_and_values_are_refused() -> None:
    rng = np.random.default_rng(SEED)
    with pytest.raises(DegenerateInput, match="exactly one value"):
        estimate_experimental(rng.uniform(size=(20, 2)), rng.standard_normal(19))


def test_coincident_points_say_what_to_check() -> None:
    points = np.zeros((40, 2))
    values = np.arange(40, dtype=float)

    with pytest.raises(DegenerateInput, match="duplicated coordinates"):
        estimate_experimental(points, values)


def test_non_finite_values_are_dropped_not_binned() -> None:
    """A NaN in a value column is missing data. Binned as a number it would
    poison every lag it appears in."""
    rng = np.random.default_rng(SEED)
    points, values = gaussian_field(rng, n=200)
    values[:5] = np.nan

    experimental = estimate_experimental(points, values, rng=rng)

    assert experimental.n_points_used == 195
    assert np.all(np.isfinite(experimental.gamma))


# --- fitting -----------------------------------------------------------------


@pytest.mark.parametrize("model", ["spherical", "exponential"])
def test_a_known_variogram_is_recovered(model: str) -> None:
    """**The reference-grade test.** `12-roadmap.md` Phase 4: "kriging with a
    known synthetic variogram recovers the field within tolerance."

    Generate from stated parameters, fit them back. A tolerance of 40% on the
    range sounds loose and is not: variogram fitting from a few hundred points
    is genuinely uncertain, and a fit landing within half an order of magnitude
    of the truth is what practitioners accept. What this catches is a fit that
    is wrong by a factor of three, which is the failure that matters.
    """
    rng = np.random.default_rng(SEED)
    points, values = gaussian_field(
        rng, n=600, extent=30_000.0, range_=5_000.0, sill=12.0, model=model
    )

    experimental = estimate_experimental(points, values, n_lags=18, rng=rng)
    fitted = fit(experimental, model)

    assert fitted.range_ == pytest.approx(5_000.0, rel=0.4)
    assert fitted.sill == pytest.approx(12.0, rel=0.5)


def test_a_pure_nugget_field_is_recognised() -> None:
    """White noise has no spatial structure, and the fit should say so rather
    than inventing a range. A nugget fraction near 1 is the signal that
    interpolation is not supported by the data."""
    rng = np.random.default_rng(SEED)
    points = rng.uniform(0.0, 20_000.0, size=(500, 2))
    values = rng.standard_normal(500) * 3.0

    fitted = fit(estimate_experimental(points, values, rng=rng))

    assert fitted.nugget_fraction > 0.6, "white noise was fitted as structured"


def test_automatic_model_selection_picks_a_plausible_family() -> None:
    """`model=None` fits every candidate and returns the best. That is the path
    Claude takes, which cannot know the property is exponential."""
    rng = np.random.default_rng(SEED)
    points, values = gaussian_field(rng, n=500, range_=4_000.0, model="spherical")

    fitted = fit(estimate_experimental(points, values, rng=rng))

    assert fitted.model in {"spherical", "exponential", "gaussian"}
    assert fitted.range_ > 0


def test_an_unknown_model_lists_the_real_ones() -> None:
    rng = np.random.default_rng(SEED)
    points, values = gaussian_field(rng, n=200)
    experimental = estimate_experimental(points, values, rng=rng)

    with pytest.raises(DegenerateInput, match="spherical"):
        fit(experimental, "kriging")


def test_detecting_anisotropy_from_a_binned_variogram_is_refused() -> None:
    """It needs directional variograms, which need the original points. Saying
    so beats returning 1.0 and letting a caller believe the field is
    isotropic."""
    rng = np.random.default_rng(SEED)
    points, values = gaussian_field(rng, n=200)
    experimental = estimate_experimental(points, values, rng=rng)

    with pytest.raises(DegenerateInput, match="fit_auto"):
        fit(experimental, detect_anisotropy=True)


# --- anisotropy detection ----------------------------------------------------


def test_an_isotropic_field_is_not_reported_as_anisotropic() -> None:
    """**The failure that matters more than missing a weak grain.**

    A ratio inside the noise, dressed up as structure, invites someone to read
    a trend that is not there. This caught two real bugs: max/min over eight
    noisy directional fits is biased upward by order statistics, and letting
    each direction choose its own lag window makes a square survey read as
    1.8:1 anisotropic at exactly 045 — the diagonal, where separations are
    1.41x longer.
    """
    rng = np.random.default_rng(SEED)
    points, values = gaussian_field(rng, n=700, range_=4_000.0)

    fitted = fit_auto(points, values, rng=rng)

    assert fitted.anisotropy_ratio == 1.0, "an isotropic field was given a grain"


def test_a_strongly_anisotropic_field_is_detected() -> None:
    """A 4:1 grain at 045 is the sort a basin margin produces, and an isotropic
    model smears it into a dome."""
    rng = np.random.default_rng(SEED)
    points, values = gaussian_field(
        rng,
        n=800,
        extent=30_000.0,
        range_=8_000.0,
        anisotropy_ratio=4.0,
        anisotropy_angle=45.0,
    )

    fitted = fit_auto(points, values, rng=rng)

    # Read conservatively — the 22.5-degree tolerance mixes directions, so a
    # true 4:1 comes back around 3:1. Under-reporting is the right direction:
    # it makes the surface slightly less elongated than the truth rather than
    # inventing elongation.
    assert fitted.anisotropy_ratio > 2.0, "a 4:1 grain was reported as isotropic"
    assert 20.0 < fitted.anisotropy_angle < 70.0, "the grain azimuth is wrong"


def test_describe_states_the_parameters_a_caption_needs() -> None:
    """`04-mcp-server.md` §6.1 puts these in render metadata so a caption can
    state them without re-deriving anything from the image."""
    variogram = FittedVariogram(
        model="exponential",
        nugget=1.1,
        sill=12.4,
        range_=4_200.0,
        anisotropy_ratio=1.8,
        anisotropy_angle=35.0,
    )

    described = variogram.describe()

    assert "exponential" in described
    assert "4,200" in described
    assert "1.8:1" in described
    assert "035" in described


def test_describe_omits_anisotropy_when_there_is_none() -> None:
    variogram = FittedVariogram(model="spherical", nugget=0.5, sill=8.0, range_=2_000.0)

    assert "anisotropy" not in variogram.describe()


# --- shape -------------------------------------------------------------------


def test_the_experimental_variogram_carries_its_pair_counts() -> None:
    """The fit weights by them: a bin holding four pairs should not pull the
    model as hard as one holding four thousand."""
    rng = np.random.default_rng(SEED)
    points, values = gaussian_field(rng, n=400)

    experimental: ExperimentalVariogram = estimate_experimental(points, values, rng=rng)

    assert len(experimental.counts) == len(experimental.lags)
    assert experimental.n_pairs > 0
    assert np.all(experimental.counts >= 30)
