"""The visual regression harness. `06-rendering.md` §10.

**Rendering bugs are visual and will not appear in unit tests.** A label that
drifts half a tile, a fill that loses its outline, a legend that stops being
drawn — every one passes a compiler test and fails on a slide.

Three deliberate choices, and the first is the one that keeps this harness
honest:

**A missing golden skips, it does not pass.** A parametrised test that silently
does nothing when its reference image is absent is worse than no test: the suite
goes green and nobody knows the case is unprotected. `tests/visual/golden/` is
empty on purpose — goldens are generated by someone who then *looks at them* —
so every case here skips with a message saying exactly how to make one.

**Goldens are never regenerated to make a test pass** (`CLAUDE.md` §7.5).
`make update-goldens` exists, writes into `golden/`, and is a deliberate act
whose diff is reviewed in the pull request.

**The tolerance is 0.1% of pixels, and it is not a knob.** It absorbs
antialiasing jitter between Chromium builds and nothing larger: a label moved by
one line, on a 2560×1440 slide, changes far more than 0.1% of the image. Raising
it to make a case pass hides exactly the class of change the harness is for.
"""

from __future__ import annotations

import json
import os
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest

HERE = Path(__file__).parent
FIXTURES = HERE / "fixtures"
GOLDEN = HERE / "golden"
OUTPUT = HERE / "output"

#: Where the render service listens. Overridable because the harness runs
#: against a container in CI and against a local process on a workstation.
RENDER_URL = os.environ.get("WEBMAP_RENDER_URL", "http://localhost:8081")

#: `06` §10's cases. Each is a fixture file in `fixtures/`, and each exists to
#: protect something specific rather than to cover surface area.
CASES: dict[str, str] = {
    "grid_with_contours_labeled": (
        "The label-placement canary. Contour labels are the most fragile thing "
        "the renderer draws: placement, collision settings, glyph loading and "
        "draw order all show up here first."
    ),
    "faults_over_grid": (
        "Draw order across source types. A fault line under a raster is a "
        "layer-ordering bug that compiles cleanly."
    ),
    "dense_point_posting": (
        "Symbol batching and overlap. Several thousand well postings is where "
        "a marker size or an allow-overlap change becomes visible."
    ),
    "graduated_polygons": (
        "The class-boundary colours, byte for byte. The shared style vectors "
        "check the expression; only a render checks what it paints."
    ),
    "continuous_ramp_legend": (
        "The legend overlay, which is HTML above the canvas — so this is also "
        "the check that the screenshot captures overlays at all."
    ),
    "transparent_background": (
        "Alpha survives the encode. A map dropped on a dark slide with a white "
        "box behind it is the failure."
    ),
}

#: Fraction of pixels that may differ. See the module docstring: not a knob.
TOLERANCE = 0.001

#: A channel difference below this is antialiasing rather than a change.
CHANNEL_THRESHOLD = 8


def pytest_addoption(parser: pytest.Parser) -> None:
    """`--update-goldens`, which `make update-goldens` calls.

    A flag rather than an environment variable, and a flag that has to be typed
    rather than a default: regenerating a golden is a deliberate act whose diff
    goes in the pull request (`CLAUDE.md` §7.5). The one thing it must never be
    is something a failing test can turn on for itself.
    """
    parser.addoption(
        "--update-goldens",
        action="store_true",
        default=False,
        help=(
            "Write the rendered image into tests/visual/golden/ instead of "
            "comparing. Review every image it writes before committing."
        ),
    )


def pytest_configure(config: pytest.Config) -> None:
    config.addinivalue_line("markers", "visual: renders a map and compares it to a golden")


@pytest.fixture(scope="session")
def updating_goldens(request: pytest.FixtureRequest) -> bool:
    return bool(request.config.getoption("--update-goldens"))


@pytest.fixture(scope="session")
def render_url() -> str:
    """The render service, or a skip that says how to start it."""
    import httpx

    try:
        httpx.get(f"{RENDER_URL}/health", timeout=5).raise_for_status()
    # Broad on purpose, and not a suppression: every way a service can be
    # unreachable — refused, DNS, TLS, timeout — becomes the same skip, and
    # the exception's type name is what makes the message specific.
    except Exception as error:
        pytest.skip(
            f"No render service at {RENDER_URL} ({type(error).__name__}). Start "
            f"it with: docker compose -f infra/compose.yaml up -d render"
        )
    return RENDER_URL


@pytest.fixture(scope="session")
def output_dir() -> Iterator[Path]:
    """Where actual images land. Gitignored, and cleared per session so a
    stale image from a previous run cannot be mistaken for this one's."""
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for stale in OUTPUT.glob("*.png"):
        stale.unlink()
    yield OUTPUT


def load_fixture(case: str) -> dict[str, Any]:
    """The render spec for a case.

    Fixtures are JSON rather than code so the same file drives the harness, the
    golden generator and a manual `curl` — a case that can only be rendered by
    running pytest is a case nobody reproduces while fixing it.
    """
    path = FIXTURES / f"{case}.json"
    if not path.is_file():
        raise FileNotFoundError(
            f"No fixture for '{case}'. Expected {path.relative_to(HERE.parent.parent)}, "
            f"holding the render spec: style, size_preset, and either bounds or "
            f"center and zoom."
        )
    spec = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(spec, dict):
        raise TypeError(
            f"{path.name} is a {type(spec).__name__}, not a render spec object."
        )
    return spec


def golden_path(case: str) -> Path:
    return GOLDEN / f"{case}.png"


def require_golden(case: str) -> Path:
    """The golden for a case, or a skip that says how to make one.

    **Skip, never pass.** A green suite that quietly checked nothing is the
    failure mode this whole file is arranged to avoid.
    """
    path = golden_path(case)
    if not path.is_file():
        pytest.skip(
            f"No golden for '{case}'. Generate one with `make update-goldens` "
            f"and **look at it** before committing — a golden is a reference "
            f"image, and one nobody reviewed makes every later diff meaningless."
        )
    return path


def compare(actual_png: bytes, golden: Path, output: Path) -> float:
    """Fraction of pixels that differ, having written the actual image out.

    Written before the comparison, not after it: a case that fails is a case
    somebody is about to look at, and an image only saved on the happy path is
    the one missing when it matters.
    """
    import numpy as np
    from PIL import Image, ImageChops

    output.write_bytes(actual_png)

    with Image.open(output) as actual_image, Image.open(golden) as golden_image:
        if actual_image.size != golden_image.size:
            raise AssertionError(
                f"Rendered {actual_image.size[0]}×{actual_image.size[1]} against a "
                f"golden of {golden_image.size[0]}×{golden_image.size[1]}. A size "
                f"change is a size-preset change, not a rendering regression — "
                f"regenerate the golden deliberately."
            )
        difference = np.asarray(
            ImageChops.difference(
                actual_image.convert("RGBA"), golden_image.convert("RGBA")
            ).convert("L")
        )
    return float((difference > CHANNEL_THRESHOLD).mean())
